import type  Metadata  from "next";


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Animates from './animations/Ant'




const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
    
   

export const Metadata = {
  title: 'বাংলা ই-কমার্স | সেরা পণ্য কিনুন',
  description: 'বাংলাদেশের সবচেয়ে নির্ভরযোগ্য অনলাইন শপিং প্ল্যাটফর্ম।',
  keywords: ['বাংলা ই-কমার্স', 'অনলাইন শপিং', 'পণ্য', 'ডিসকাউন্ট'],
  metadataBase: new URL('https://yourdomain.com'), // আপনার ডোমেইন
  authors: [{ name: 'আপনার নাম', url: 'https://yourdomain.com' }],
  openGraph: {
    title: 'বাংলা ই-কমার্স',
    description: 'সেরা পণ্য, সবচেয়ে কম দামে কিনুন!',
    url: 'https://yourdomain.com',
    siteName: 'বাংলা ই-কমার্স',
    locale: 'bn_BD',
    type: 'website',
    images: [
      {
        url: '/seo-cover.jpg',
        width: 1200,
        height: 630,
        alt: 'বাংলা ই-কমার্স কভার',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'বাংলা ই-কমার্স',
    description: 'বাংলাদেশের টপ অনলাইন শপিং প্ল্যাটফর্ম!',
    images: ['/seo-cover.jpg'],
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
};
//export const metadata: Metadata = {
 // title: "Create Next App",
//discription: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
<Toaster position="top-center" reverseOrder={false} />

 <Animates /> 


        {children}
      </body>
    </html>
  );
}
